export const board = [
	{
		name: "Gregory Kurtzer",
		image: "/gregk.jpeg",
		role: "President, Chair",
		country: "USA",
		active: true,
		bio: "Founder of CentOS, Rocky Linux, and other open source projects. Dedicated to creating sustainable enterprise open source communities.",
		socials: {
			linkedIn: "https://www.linkedin.com/in/gmkurtzer/",
			bluesky: "https://bsky.app/profile/gmkurtzer.bsky.social",
			email: "mailto:gmk@resf.org",
		},
	},
	{
		name: "Brian Clemens",
		image: "/brianc.png",
		role: "Vice President",
		country: "Japan",
		active: true,
		hoverText: "Brian does not use a photo due to privacy concerns.",
		socials: {
			website: "https://tiuxo.com",
			bluesky: "https://bsky.app/profile/tiuxo.com",
			mastodon: "https://gts.tiuxo.com/@brian",
			email: "mailto:brian@resf.org",
		},
	},
	{
		name: "Christopher Stackpole",
		image: "/christophers.jpg",
		role: "Board Member",
		country: "USA",
		active: true,
		socials: {
			email: "mailto:stack@rockylinux.org",
		},
	},
	{
		name: "Mustafa Gezen",
		image: "/mustafag.jpg",
		role: "Board Member",
		country: "Norway",
		active: true,
		socials: {
			linkedIn: "https://www.linkedin.com/in/mustafa-gezen/",
			bluesky: "https://bsky.app/profile/mstg.bsky.social",
			email: "mailto:mustafa@rockylinux.org",
		},
	},
	{
		name: "Neil Hanlon",
		image: "/neilh.png",
		role: "Board Member",
		country: "USA",
		active: true,
		socials: {
			website: "https://shrug.pw",
			linkedIn: "https://www.linkedin.com/in/hanlonneil/",
			bluesky: "https://bsky.app/profile/shrug.pw",
			email: "mailto:neil@resf.org",
		}
	},
	{
		name: "Sherif Nagy",
		image: "/sherifn.jpeg",
		role: "Board Member",
		country: "Ireland",
		active: true,
		socials: {
			linkedIn: "https://www.linkedin.com/in/sherifn/",
			bluesky: "https://bsky.app/profile/gnulab.org",
			email: "mailto:sherif@rockylinux.org",
		},
	},
	{
		name: "Taylor Goodwill",
		image: "/taylorg.jpg",
		role: "Board Member",
		country: "USA",
		active: true,
		socials: {
			linkedIn: "https://www.linkedin.com/in/taylorgoodwill/",
			bluesky: "https://bsky.app/profile/limin.nl",
			email: "mailto:tg@resf.org",
		},
	},
	{
		name: "Buyanjargal Shirnen",
		image: "/buyas.jpg",
		role: "Independent",
		country: "Japan",
		active: true,
		socials: {
			linkedIn: "https://www.linkedin.com/in/buyanjargal-shirnen/",
		},
	},
	{
		name: "Mark Watson",
		image: "/markw.png",
		role: "Independent",
		country: "USA",
		active: false,
		socials: {
			linkedIn: "https://www.linkedin.com/in/mark-a-watson-9035b59/",
		},
	},
	{
		name: "Christopher DiBona",
		image: "/christopherd.jpg",
		role: "Independent",
		country: "USA",
		active: true,
		socials: {
			linkedIn: "https://www.linkedin.com/in/cdibona/",
			bluesky: "https://bsky.app/profile/cdibona.bsky.social",
		},
	},
	{
		name: "Benjamin Agner",
		image: "/benjamina.jpg",
		role: "Independent",
		country: "USA",
		active: true,
		socials: {
			linkedIn: "https://www.linkedin.com/in/benjaminagner/",
		},
	},
	{
		name: "Theodore Ts'o",
		image: "/theodoret.jpg",
		role: "Independent",
		country: "USA",
		active: true,
		socials: {
			linkedIn: "https://www.linkedin.com/in/tytso/",
		},
	},
	{
		name: "Greg Kroah-Hartman",
		image: "/gregkh.jpg",
		role: "Independent",
		country: "USA",
		active: false,
		socials: {
			website: "http://www.kroah.com/log",
			mastodon: "https://social.kernel.org/users/gregkh",
			linkedIn: "https://www.linkedin.com/in/greg-kroah-hartman/",
		},
	},
];
